[features]
seeds = false
skip-lint = false
[programs.devnet]
token_presale = "9BULjGux5mbKFJPKHVHPeWGzeveEaEHkhoLLANynAPcD"

[registry]
url = "https://api.devnet.solana.com/"

[provider]
cluster = "devnet"
wallet = "./token_presale-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
